import { Outfit } from "next/font/google";
import NextUIThemeProvider from "@/config/provider/NextUIThemeProvider";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <main className="min-h-screen dark text-foreground bg-background">
          <NextUIThemeProvider>{children}</NextUIThemeProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
